# Generated by Django 5.1.1 on 2024-12-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtabs_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='event',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='to_do_list',
        ),
        migrations.AddField(
            model_name='reminder',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
