# Generated by Django 5.1.1 on 2024-12-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtabs_app', '0002_remove_reminder_description_remove_reminder_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_id',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
