# Generated by Django 5.1.1 on 2024-11-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtabs_app', '0003_task_created_at_task_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
